//===- MutOptsHandle.h - Scoped mutators for option structs -----*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Defines per-Options mutator handle classes that callers receive inside a
/// \c CompilerInvocation::withMut*Opts() callback. Each handle exposes only
/// per-field setters generated from the corresponding \c *Options.def, and
/// is non-copyable / non-movable so the underlying option object cannot be
/// aliased out of the callback.
///
//===----------------------------------------------------------------------===//

#ifndef LLVM_CLANG_FRONTEND_MUTOPTSHANDLE_H
#define LLVM_CLANG_FRONTEND_MUTOPTSHANDLE_H

#include "clang/APINotes/APINotesOptions.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/DiagnosticOptions.h"
#include "clang/Basic/FileSystemOptions.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/TargetOptions.h"
#include "clang/Frontend/DependencyOutputOptions.h"
#include "clang/Frontend/FrontendOptions.h"
#include "clang/Frontend/MigratorOptions.h"
#include "clang/Frontend/PreprocessorOutputOptions.h"
#include "clang/Lex/HeaderSearchOptions.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "clang/StaticAnalyzer/Core/AnalyzerOptions.h"

#include <utility>

namespace clang {

class CompilerInvocation;

/// Common boilerplate for per-Options mutator handles.
///
/// Handles are constructed only by \c CompilerInvocation::withMut*Opts(),
/// which befriends derived classes. They are non-copyable and non-movable, so
/// the wrapped reference cannot escape the callback. The only general-purpose
/// mutator the base provides is \c replace(), which whole-struct-assigns the
/// underlying options object; per-field setters are generated by the derived
/// class via re-including the corresponding \c *Options.def.
template <typename T> class MutOptsHandleBase {
public:
  MutOptsHandleBase(const MutOptsHandleBase &) = delete;
  MutOptsHandleBase(MutOptsHandleBase &&) = delete;
  MutOptsHandleBase &operator=(const MutOptsHandleBase &) = delete;
  MutOptsHandleBase &operator=(MutOptsHandleBase &&) = delete;

  /// Replace the entire options struct (used by AST-replay paths that
  /// inherit options from a loaded AST file).
  void replace(const T &New) { O = New; }

protected:
  T &O;
  explicit MutOptsHandleBase(T &O) : O(O) {}
};

#define MUT_OPTS_HANDLE_BOILERPLATE(HandleName, OptsType)                      \
  using MutOptsHandleBase<OptsType>::MutOptsHandleBase;                        \
  friend class clang::CompilerInvocation;

class MutLangOptsHandle : public MutOptsHandleBase<LangOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutLangOptsHandle, LangOptions)
public:
  using MacroPrefixMapType = LangOptions::MacroPrefixMapType;
  // Forward in-class enum types so the .def's ENUM_LANGOPT(... Type ...)
  // entries resolve as bare names inside this handle.
  using AltivecSrcCompatKind = LangOptions::AltivecSrcCompatKind;
  using ComplexRangeKind = LangOptions::ComplexRangeKind;
  using CompilingModuleKind = LangOptions::CompilingModuleKind;
  using CoreFoundationABI = LangOptions::CoreFoundationABI;
  using DefaultCallingConvention = LangOptions::DefaultCallingConvention;
  using DefaultVisiblityExportMapping =
      LangOptions::DefaultVisiblityExportMapping;
  using ExcessPrecisionKind = LangOptions::ExcessPrecisionKind;
  using ExtendArgsKind = LangOptions::ExtendArgsKind;
  using GPUDefaultStreamKind = LangOptions::GPUDefaultStreamKind;
  using FPEvalMethodKind = LangOptions::FPEvalMethodKind;
  using AddrSpaceMapMangling = LangOptions::AddrSpaceMapMangling;
  using ClangABI = LangOptions::ClangABI;
  using MatrixMemoryLayout = LangOptions::MatrixMemoryLayout;
  using RegisterStaticDestructorsKind =
      LangOptions::RegisterStaticDestructorsKind;
  using StackProtectorMode = LangOptions::StackProtectorMode;
  using TrivialAutoVarInitKind = LangOptions::TrivialAutoVarInitKind;
  using FPExceptionModeKind = LangOptions::FPExceptionModeKind;
  using FPModeKind = LangOptions::FPModeKind;
  using GCMode = LangOptions::GCMode;
  using HLSLLangStd = LangOptions::HLSLLangStd;
  using LaxVectorConversionKind = LangOptions::LaxVectorConversionKind;
  using LayoutCompatibilityKind = LangOptions::LayoutCompatibilityKind;
  using MSVtorDispMode = LangOptions::MSVtorDispMode;
  using PragmaMSPointersToMembersKind =
      LangOptions::PragmaMSPointersToMembersKind;
  using SYCLMajorVersion = LangOptions::SYCLMajorVersion;
  using SignReturnAddressKeyKind = LangOptions::SignReturnAddressKeyKind;
  using SignReturnAddressScopeKind = LangOptions::SignReturnAddressScopeKind;
  using SignedOverflowBehaviorTy = LangOptions::SignedOverflowBehaviorTy;
  using StrictFlexArraysLevelKind = LangOptions::StrictFlexArraysLevelKind;
  using ThreadModelKind = LangOptions::ThreadModelKind;
  using VisibilityForcedKinds = LangOptions::VisibilityForcedKinds;
  using VisibilityFromDLLStorageClassKinds =
      LangOptions::VisibilityFromDLLStorageClassKinds;
#define LANGOPT(Name, Bits, Default, Compatibility, Description)               \
  void set##Name(unsigned V) { O.Name = V; }
#define ENUM_LANGOPT(Name, Type, Bits, Default, Compatibility, Description)    \
  void set##Name(Type V) { O.set##Name(V); }
#define TYPED_LANGOPT(Type, Name, Default)                                     \
  void set##Name(Type V) { O.Name = std::move(V); }
#include "clang/Basic/LangOptions.def"
#undef TYPED_LANGOPT
};

class MutTargetOptsHandle : public MutOptsHandleBase<TargetOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutTargetOptsHandle, TargetOptions)
public:
  using StringBoolMap = TargetOptions::StringBoolMap;
  using AMDGPUPrintfKind = TargetOptions::AMDGPUPrintfKind;
#define TYPED_TARGETOPT(Type, Name, Default)                                   \
  void set##Name(Type V) { O.Name = std::move(V); }
#include "clang/Basic/TargetOptions.def"
#undef TYPED_TARGETOPT
};

class MutDiagnosticOptsHandle : public MutOptsHandleBase<DiagnosticOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutDiagnosticOptsHandle, DiagnosticOptions)
public:
  using TextDiagnosticFormat = DiagnosticOptions::TextDiagnosticFormat;
#define DIAGOPT(Name, Bits, Default)                                           \
  void set##Name(unsigned V) { O.Name = V; }
#define ENUM_DIAGOPT(Name, Type, Bits, Default)                                \
  void set##Name(Type V) { O.set##Name(V); }
#define TYPED_DIAGOPT(Type, Name, Default)                                     \
  void set##Name(Type V) { O.Name = std::move(V); }
#include "clang/Basic/DiagnosticOptions.def"
#undef TYPED_DIAGOPT
};

class MutHeaderSearchOptsHandle
    : public MutOptsHandleBase<HeaderSearchOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutHeaderSearchOptsHandle, HeaderSearchOptions)
public:
  using Entry = HeaderSearchOptions::Entry;
  using SystemHeaderPrefix = HeaderSearchOptions::SystemHeaderPrefix;
  using PrebuiltModuleFilesMap = HeaderSearchOptions::PrebuiltModuleFilesMap;
  using ModulesIgnoreMacrosSet = HeaderSearchOptions::ModulesIgnoreMacrosSet;
#define TYPED_HEADERSEARCHOPT(Type, Name, Default)                             \
  void set##Name(Type V) { O.Name = std::move(V); }
#define BITFIELD_HEADERSEARCHOPT(Type, Name, Bits, Default)                    \
  void set##Name(Type V) { O.Name = static_cast<unsigned>(V); }
#include "clang/Lex/HeaderSearchOptions.def"
#undef TYPED_HEADERSEARCHOPT
#undef BITFIELD_HEADERSEARCHOPT
};

class MutPreprocessorOptsHandle
    : public MutOptsHandleBase<PreprocessorOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutPreprocessorOptsHandle, PreprocessorOptions)
public:
  using MacroDef = PreprocessorOptions::MacroDef;
  using PreambleBytes = PreprocessorOptions::PreambleBytes;
  using RemappedFile = PreprocessorOptions::RemappedFile;
  using RemappedFileBuffer = PreprocessorOptions::RemappedFileBuffer;
#define TYPED_PREPROCESSOROPT(Type, Name, Default)                             \
  void set##Name(Type V) { O.Name = std::move(V); }
#include "clang/Lex/PreprocessorOptions.def"
#undef TYPED_PREPROCESSOROPT
};

class MutAnalyzerOptsHandle : public MutOptsHandleBase<AnalyzerOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutAnalyzerOptsHandle, AnalyzerOptions)
public:
  using ConfigTable = AnalyzerOptions::ConfigTable;
  using CheckerOrPackagePair = AnalyzerOptions::CheckerOrPackagePair;
#define TYPED_ANALYZEROPT(Type, Name, Default)                                 \
  void set##Name(Type V) { O.Name = std::move(V); }
#define BITFIELD_ANALYZEROPT(Type, Name, Bits, Default)                        \
  void set##Name(Type V) { O.Name = static_cast<unsigned>(V); }
#include "clang/StaticAnalyzer/Core/AnalyzerOptions.def"
#undef TYPED_ANALYZEROPT
#undef BITFIELD_ANALYZEROPT
};

class MutMigratorOptsHandle : public MutOptsHandleBase<MigratorOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutMigratorOptsHandle, MigratorOptions)
public:
#define TYPED_MIGRATOROPT(Type, Name, Default)                                 \
  void set##Name(Type V) { O.Name = std::move(V); }
#define BITFIELD_MIGRATOROPT(Type, Name, Bits, Default)                        \
  void set##Name(Type V) { O.Name = static_cast<unsigned>(V); }
#include "clang/Frontend/MigratorOptions.def"
#undef TYPED_MIGRATOROPT
#undef BITFIELD_MIGRATOROPT
};

class MutAPINotesOptsHandle : public MutOptsHandleBase<APINotesOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutAPINotesOptsHandle, APINotesOptions)
public:
#define TYPED_APINOTESOPT(Type, Name, Default)                                 \
  void set##Name(Type V) { O.Name = std::move(V); }
#include "clang/APINotes/APINotesOptions.def"
#undef TYPED_APINOTESOPT
};

class MutCodeGenOptsHandle : public MutOptsHandleBase<CodeGenOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutCodeGenOptsHandle, CodeGenOptions)
public:
  using StringPairList = CodeGenOptions::StringPairList;
  using PassBuilderCallbackList = CodeGenOptions::PassBuilderCallbackList;
  using BitcodeFileToLink = CodeGenOptions::BitcodeFileToLink;
  using OptRemark = CodeGenOptions::OptRemark;
  // Forward in-class enum types so the .def's ENUM_CODEGENOPT(... Type ...)
  // entries resolve as bare names inside this handle.
  using AsanDetectStackUseAfterReturnMode =
      CodeGenOptions::AsanDetectStackUseAfterReturnMode;
  using AsanDtorKind = CodeGenOptions::AsanDtorKind;
  using BoolFromMem = CodeGenOptions::BoolFromMem;
  using CFBranchLabelSchemeKind = CodeGenOptions::CFBranchLabelSchemeKind;
  using ControlFlowGuardMechanism = CodeGenOptions::ControlFlowGuardMechanism;
  using DebugCompressionType = CodeGenOptions::DebugCompressionType;
  using DebugInfoKind = CodeGenOptions::DebugInfoKind;
  using DebugTemplateNamesKind = CodeGenOptions::DebugTemplateNamesKind;
  using DebuggerKind = CodeGenOptions::DebuggerKind;
  using EmbedBitcodeKind = CodeGenOptions::EmbedBitcodeKind;
  using EmitDwarfUnwindType = CodeGenOptions::EmitDwarfUnwindType;
  using ExceptionHandlingKind = CodeGenOptions::ExceptionHandlingKind;
  using ExtendVariableLivenessKind =
      CodeGenOptions::ExtendVariableLivenessKind;
  using FiniteLoopsKind = CodeGenOptions::FiniteLoopsKind;
  using FramePointerKind = CodeGenOptions::FramePointerKind;
  using InliningMethod = CodeGenOptions::InliningMethod;
  using InlineAsmDialectKind = CodeGenOptions::InlineAsmDialectKind;
  using ObjCDispatchMethodKind = CodeGenOptions::ObjCDispatchMethodKind;
  using ProfileInstrKind = CodeGenOptions::ProfileInstrKind;
  using RelocSectionSymType = CodeGenOptions::RelocSectionSymType;
  using SanitizeDebugTrapReasonKind =
      CodeGenOptions::SanitizeDebugTrapReasonKind;
  using StructReturnConventionKind = CodeGenOptions::StructReturnConventionKind;
  using SwiftAsyncFramePointerKind = CodeGenOptions::SwiftAsyncFramePointerKind;
  using TLSModel = CodeGenOptions::TLSModel;
  using VectorLibrary = CodeGenOptions::VectorLibrary;
  using WinX64EHUnwindMode = CodeGenOptions::WinX64EHUnwindMode;
  using ZeroCallUsedRegsKind = CodeGenOptions::ZeroCallUsedRegsKind;
  using AssignmentTrackingOpts = CodeGenOptions::AssignmentTrackingOpts;
  using DebugSrcHashKind = CodeGenOptions::DebugSrcHashKind;
#define CODEGENOPT(Name, Bits, Default, Compatibility)                         \
  void set##Name(unsigned V) { O.Name = V; }
#define ENUM_CODEGENOPT(Name, Type, Bits, Default, Compatibility)              \
  void set##Name(Type V) { O.set##Name(V); }
#define TYPED_CODEGENOPT(Type, Name, Default)                                  \
  void set##Name(Type V) { O.Name = std::move(V); }
#include "clang/Basic/CodeGenOptions.def"
#undef TYPED_CODEGENOPT
};

class MutFileSystemOptsHandle : public MutOptsHandleBase<FileSystemOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutFileSystemOptsHandle, FileSystemOptions)
public:
#define TYPED_FILESYSTEMOPT(Type, Name, Default)                               \
  void set##Name(Type V) { O.Name = std::move(V); }
#include "clang/Basic/FileSystemOptions.def"
#undef TYPED_FILESYSTEMOPT
};

class MutFrontendOptsHandle : public MutOptsHandleBase<FrontendOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutFrontendOptsHandle, FrontendOptions)
public:
  using PluginArgsMap = FrontendOptions::PluginArgsMap;
  using InputsList = FrontendOptions::InputsList;
  using ModuleFileExtensionList = FrontendOptions::ModuleFileExtensionList;
#define TYPED_FRONTENDOPT(Type, Name, Default)                                 \
  void set##Name(Type V) { O.Name = std::move(V); }
#define BITFIELD_FRONTENDOPT(Type, Name, Bits, Default)                        \
  void set##Name(Type V) { O.Name = static_cast<unsigned>(V); }
#include "clang/Frontend/FrontendOptions.def"
#undef TYPED_FRONTENDOPT
#undef BITFIELD_FRONTENDOPT
};

class MutDependencyOutputOptsHandle
    : public MutOptsHandleBase<DependencyOutputOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutDependencyOutputOptsHandle,
                              DependencyOutputOptions)
public:
  using ExtraDep = DependencyOutputOptions::ExtraDep;
#define TYPED_DEPOUTPUTOPT(Type, Name, Default)                                \
  void set##Name(Type V) { O.Name = std::move(V); }
#define BITFIELD_DEPOUTPUTOPT(Type, Name, Bits, Default)                       \
  void set##Name(Type V) { O.Name = static_cast<unsigned>(V); }
#include "clang/Frontend/DependencyOutputOptions.def"
#undef TYPED_DEPOUTPUTOPT
#undef BITFIELD_DEPOUTPUTOPT
};

class MutPreprocessorOutputOptsHandle
    : public MutOptsHandleBase<PreprocessorOutputOptions> {
  MUT_OPTS_HANDLE_BOILERPLATE(MutPreprocessorOutputOptsHandle,
                              PreprocessorOutputOptions)
public:
#define TYPED_PPOUTPUTOPT(Type, Name, Default)                                 \
  void set##Name(Type V) { O.Name = std::move(V); }
#define BITFIELD_PPOUTPUTOPT(Type, Name, Bits, Default)                        \
  void set##Name(Type V) { O.Name = static_cast<unsigned>(V); }
#include "clang/Frontend/PreprocessorOutputOptions.def"
#undef TYPED_PPOUTPUTOPT
#undef BITFIELD_PPOUTPUTOPT
};

#undef MUT_OPTS_HANDLE_BOILERPLATE

} // namespace clang

#endif // LLVM_CLANG_FRONTEND_MUTOPTSHANDLE_H
